services:
  redis:
    image: redis:8-alpine
    ports:
      - 6379:6379
    networks:
      - datastore
    volumes:
      - redis_data:/data

  vault:
    image: hashicorp/vault:1.21
    ports:
      - 8200:8200
    networks:
      - datastore
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
      VAULT_DEV_ROOT_TOKEN_ID: vault-admin
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200

  api:
    image: registry.gitlab.com/cellar-app/cellar-api:3.3.1
    ports:
      - 8081:8080
    networks:
      - datastore
    depends_on:
      - redis
      - vault
    environment:
      APP_CLIENT_ADDRESS: 127.0.0.1:8081
      DATASTORE_REDIS_HOST: redis
      DATASTORE_REDIS_PORT: 6379
      DISABLE_SWAGGER:
      LOGGING_LEVEL: "DEBUG"
      CRYPTOGRAPHY_VAULT_ADDRESS: http://vault:8200
      CRYPTOGRAPHY_VAULT_ENCRYPTION_TOKEN_NAME: cellar-key
      CRYPTOGRAPHY_VAULT_AUTH_MOUNT_PATH: approle
    env_file:
      - .env

  playwright:
    image: mcr.microsoft.com/playwright:v1.57.0-noble
    networks:
      - datastore
    depends_on:
      - api
      - redis
      - vault
    ports:
      - "5173:5173" # Expose UI port for debugging
    ipc: host
    user: pwuser
    init: true
    command: ["tail", "-f", "/dev/null"]
    environment:
      DOCKER: "true"
      PLAYWRIGHT_BROWSERS_PATH: /ms-playwright
      BIND_ADDRESS: api:8080
      REDIS_HOST: redis
      REDIS_PORT: 6379
      VAULT_ADDRESS: http://vault:8200
      VAULT_DEV_ROOT_TOKEN_ID: vault-admin
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_LOCAL_ADDR: http://vault:8200
      VAULT_ROOT_TOKEN: vault-admin
      VAULT_TOKEN_NAME: cellar-testing
      # Host variables
      HOST: "0.0.0.0"
      # WebKit-specific variables
      WEBKIT_NETWORK_CONNECTION_MODE: "shared"
      BROWSER_TIMEOUT: "60000"
    working_dir: /app
    env_file:
      - .env


volumes:
  redis_data:


networks:
  datastore:
